// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avlbdqqwldjteafmzwjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2bGJkcXF3bGRqdGVhZm16d2piIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzNjA0MDgsImV4cCI6MjA3NTkzNjQwOH0.-ihQH7W23x8MdXbvnLScFer2C0YSVEzCoqVKUjC-5hQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});